services:
  # ----------------------------------------------------
  # 1. BASES DE DATOS
  # ----------------------------------------------------
  # POSTGRESQL
  postgres_service:
    image: postgres:18.1-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sql_cypher_translator_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5

  # SQL SERVER
  sqlserver_service:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_SERVER_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sql_cypher_translator_net

  # NEO4J
  neo4j_service:
    image: neo4j:2025.11.2-community
    container_name: neo4j_db
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_pagecache_size=512M
    volumes:
      - neo4j_data:/data
    networks:
      - sql_cypher_translator_net


# ----------------------------------------------------
# 2. BACKEND
# ----------------------------------------------------
  backend_service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: translator_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_SERVER=postgres_service
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SQLSERVER_HOST=sqlserver_service
      - NEO4J_URI=bolt://neo4j_service:7687
    depends_on:
      postgres_service:
        condition: service_healthy
    networks:
      - sql_cypher_translator_net

# ----------------------------------------------------
# 3. FRONTEND
# ----------------------------------------------------
  frontend_service:
    build:
      context: ../frontend-middleware
      dockerfile: Dockerfile
    container_name: translator_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend_service:8000/api/v1
    depends_on:
      - backend_service
    networks:
      - sql_cypher_translator_net

# ----------------------------------------------------
# Vol√∫menes y Redes
# ----------------------------------------------------
volumes:
  postgres_data:
  sqlserver_data:
  neo4j_data:

networks:
  sql_cypher_translator_net:
    driver: bridge